// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xescugc/pikoci/pikoci/build (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/build_repository.go -mock_names=Repository=BuildRepository -package mock github.com/xescugc/pikoci/pikoci/build Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	build "github.com/xescugc/pikoci/pikoci/build"
	gomock "go.uber.org/mock/gomock"
)

// BuildRepository is a mock of Repository interface.
type BuildRepository struct {
	ctrl     *gomock.Controller
	recorder *BuildRepositoryMockRecorder
	isgomock struct{}
}

// BuildRepositoryMockRecorder is the mock recorder for BuildRepository.
type BuildRepositoryMockRecorder struct {
	mock *BuildRepository
}

// NewBuildRepository creates a new mock instance.
func NewBuildRepository(ctrl *gomock.Controller) *BuildRepository {
	mock := &BuildRepository{ctrl: ctrl}
	mock.recorder = &BuildRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *BuildRepository) EXPECT() *BuildRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *BuildRepository) Create(ctx context.Context, tc, pn, jn string, b build.Build) (uint32, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tc, pn, jn, b)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Create indicates an expected call of Create.
func (mr *BuildRepositoryMockRecorder) Create(ctx, tc, pn, jn, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*BuildRepository)(nil).Create), ctx, tc, pn, jn, b)
}

// Delete mocks base method.
func (m *BuildRepository) Delete(ctx context.Context, tc, pn, jn, buildNumber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tc, pn, jn, buildNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *BuildRepositoryMockRecorder) Delete(ctx, tc, pn, jn, buildNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*BuildRepository)(nil).Delete), ctx, tc, pn, jn, buildNumber)
}

// Filter mocks base method.
func (m *BuildRepository) Filter(ctx context.Context, tc, pn, jn string) ([]*build.Build, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, tc, pn, jn)
	ret0, _ := ret[0].([]*build.Build)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *BuildRepositoryMockRecorder) Filter(ctx, tc, pn, jn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*BuildRepository)(nil).Filter), ctx, tc, pn, jn)
}

// Find mocks base method.
func (m *BuildRepository) Find(ctx context.Context, tc, pn, jn, buildNumber string) (*build.Build, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, tc, pn, jn, buildNumber)
	ret0, _ := ret[0].(*build.Build)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *BuildRepositoryMockRecorder) Find(ctx, tc, pn, jn, buildNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*BuildRepository)(nil).Find), ctx, tc, pn, jn, buildNumber)
}

// FindReadyDownstreamVersion mocks base method.
func (m *BuildRepository) FindReadyDownstreamVersion(ctx context.Context, tc, pn string, upstreamJobs []string, downstreamJob, stepName string, upstreamCount int) (uint32, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindReadyDownstreamVersion", ctx, tc, pn, upstreamJobs, downstreamJob, stepName, upstreamCount)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindReadyDownstreamVersion indicates an expected call of FindReadyDownstreamVersion.
func (mr *BuildRepositoryMockRecorder) FindReadyDownstreamVersion(ctx, tc, pn, upstreamJobs, downstreamJob, stepName, upstreamCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindReadyDownstreamVersion", reflect.TypeOf((*BuildRepository)(nil).FindReadyDownstreamVersion), ctx, tc, pn, upstreamJobs, downstreamJob, stepName, upstreamCount)
}

// InsertGetVersion mocks base method.
func (m *BuildRepository) InsertGetVersion(ctx context.Context, tc, pn, jn string, buildID uint32, stepName string, versionID uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertGetVersion", ctx, tc, pn, jn, buildID, stepName, versionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertGetVersion indicates an expected call of InsertGetVersion.
func (mr *BuildRepositoryMockRecorder) InsertGetVersion(ctx, tc, pn, jn, buildID, stepName, versionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertGetVersion", reflect.TypeOf((*BuildRepository)(nil).InsertGetVersion), ctx, tc, pn, jn, buildID, stepName, versionID)
}

// LastBuildAtByPipeline mocks base method.
func (m *BuildRepository) LastBuildAtByPipeline(ctx context.Context, tc string) (map[uint32]time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastBuildAtByPipeline", ctx, tc)
	ret0, _ := ret[0].(map[uint32]time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastBuildAtByPipeline indicates an expected call of LastBuildAtByPipeline.
func (mr *BuildRepositoryMockRecorder) LastBuildAtByPipeline(ctx, tc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastBuildAtByPipeline", reflect.TypeOf((*BuildRepository)(nil).LastBuildAtByPipeline), ctx, tc)
}

// Update mocks base method.
func (m *BuildRepository) Update(ctx context.Context, tc, pn, jn, buildNumber string, b build.Build) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tc, pn, jn, buildNumber, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *BuildRepositoryMockRecorder) Update(ctx, tc, pn, jn, buildNumber, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*BuildRepository)(nil).Update), ctx, tc, pn, jn, buildNumber, b)
}
