// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xescugc/pikoci/pikoci/pipeline (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/pipeline_repository.go -mock_names=Repository=PipelineRepository -package mock github.com/xescugc/pikoci/pikoci/pipeline Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	pipeline "github.com/xescugc/pikoci/pikoci/pipeline"
	gomock "go.uber.org/mock/gomock"
)

// PipelineRepository is a mock of Repository interface.
type PipelineRepository struct {
	ctrl     *gomock.Controller
	recorder *PipelineRepositoryMockRecorder
	isgomock struct{}
}

// PipelineRepositoryMockRecorder is the mock recorder for PipelineRepository.
type PipelineRepositoryMockRecorder struct {
	mock *PipelineRepository
}

// NewPipelineRepository creates a new mock instance.
func NewPipelineRepository(ctrl *gomock.Controller) *PipelineRepository {
	mock := &PipelineRepository{ctrl: ctrl}
	mock.recorder = &PipelineRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *PipelineRepository) EXPECT() *PipelineRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *PipelineRepository) Create(ctx context.Context, tc string, pp pipeline.Pipeline) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tc, pp)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *PipelineRepositoryMockRecorder) Create(ctx, tc, pp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*PipelineRepository)(nil).Create), ctx, tc, pp)
}

// Delete mocks base method.
func (m *PipelineRepository) Delete(ctx context.Context, tc, pn string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tc, pn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *PipelineRepositoryMockRecorder) Delete(ctx, tc, pn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*PipelineRepository)(nil).Delete), ctx, tc, pn)
}

// Filter mocks base method.
func (m *PipelineRepository) Filter(ctx context.Context, tc string) ([]*pipeline.Pipeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, tc)
	ret0, _ := ret[0].([]*pipeline.Pipeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *PipelineRepositoryMockRecorder) Filter(ctx, tc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*PipelineRepository)(nil).Filter), ctx, tc)
}

// FilterAll mocks base method.
func (m *PipelineRepository) FilterAll(ctx context.Context) ([]*pipeline.WithTeam, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterAll", ctx)
	ret0, _ := ret[0].([]*pipeline.WithTeam)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterAll indicates an expected call of FilterAll.
func (mr *PipelineRepositoryMockRecorder) FilterAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterAll", reflect.TypeOf((*PipelineRepository)(nil).FilterAll), ctx)
}

// Find mocks base method.
func (m *PipelineRepository) Find(ctx context.Context, tc, pn string) (*pipeline.Pipeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, tc, pn)
	ret0, _ := ret[0].(*pipeline.Pipeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *PipelineRepositoryMockRecorder) Find(ctx, tc, pn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*PipelineRepository)(nil).Find), ctx, tc, pn)
}

// FindPublic mocks base method.
func (m *PipelineRepository) FindPublic(ctx context.Context, tc, pn string) (*pipeline.Pipeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPublic", ctx, tc, pn)
	ret0, _ := ret[0].(*pipeline.Pipeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPublic indicates an expected call of FindPublic.
func (mr *PipelineRepositoryMockRecorder) FindPublic(ctx, tc, pn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPublic", reflect.TypeOf((*PipelineRepository)(nil).FindPublic), ctx, tc, pn)
}

// SetPublic mocks base method.
func (m *PipelineRepository) SetPublic(ctx context.Context, tc, pn string, public bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPublic", ctx, tc, pn, public)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPublic indicates an expected call of SetPublic.
func (mr *PipelineRepositoryMockRecorder) SetPublic(ctx, tc, pn, public any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPublic", reflect.TypeOf((*PipelineRepository)(nil).SetPublic), ctx, tc, pn, public)
}

// Update mocks base method.
func (m *PipelineRepository) Update(ctx context.Context, tc, ppn string, pp pipeline.Pipeline) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tc, ppn, pp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *PipelineRepositoryMockRecorder) Update(ctx, tc, ppn, pp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*PipelineRepository)(nil).Update), ctx, tc, ppn, pp)
}
