// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xescugc/pikoci/pikoci/resource (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/resource_repository.go -mock_names=Repository=ResourceRepository -package mock github.com/xescugc/pikoci/pikoci/resource Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	resource "github.com/xescugc/pikoci/pikoci/resource"
	gomock "go.uber.org/mock/gomock"
)

// ResourceRepository is a mock of Repository interface.
type ResourceRepository struct {
	ctrl     *gomock.Controller
	recorder *ResourceRepositoryMockRecorder
	isgomock struct{}
}

// ResourceRepositoryMockRecorder is the mock recorder for ResourceRepository.
type ResourceRepositoryMockRecorder struct {
	mock *ResourceRepository
}

// NewResourceRepository creates a new mock instance.
func NewResourceRepository(ctrl *gomock.Controller) *ResourceRepository {
	mock := &ResourceRepository{ctrl: ctrl}
	mock.recorder = &ResourceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ResourceRepository) EXPECT() *ResourceRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *ResourceRepository) Create(ctx context.Context, tc, pn string, r resource.Resource) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tc, pn, r)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *ResourceRepositoryMockRecorder) Create(ctx, tc, pn, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*ResourceRepository)(nil).Create), ctx, tc, pn, r)
}

// CreateVersion mocks base method.
func (m *ResourceRepository) CreateVersion(ctx context.Context, tc, pn, rCan string, v resource.Version) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVersion", ctx, tc, pn, rCan, v)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVersion indicates an expected call of CreateVersion.
func (mr *ResourceRepositoryMockRecorder) CreateVersion(ctx, tc, pn, rCan, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVersion", reflect.TypeOf((*ResourceRepository)(nil).CreateVersion), ctx, tc, pn, rCan, v)
}

// Delete mocks base method.
func (m *ResourceRepository) Delete(ctx context.Context, tc, pn, rCan string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tc, pn, rCan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *ResourceRepositoryMockRecorder) Delete(ctx, tc, pn, rCan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*ResourceRepository)(nil).Delete), ctx, tc, pn, rCan)
}

// Filter mocks base method.
func (m *ResourceRepository) Filter(ctx context.Context, tc, pn string) ([]*resource.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, tc, pn)
	ret0, _ := ret[0].([]*resource.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *ResourceRepositoryMockRecorder) Filter(ctx, tc, pn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*ResourceRepository)(nil).Filter), ctx, tc, pn)
}

// FilterDueResources mocks base method.
func (m *ResourceRepository) FilterDueResources(ctx context.Context) ([]*resource.ResourceWithPipeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterDueResources", ctx)
	ret0, _ := ret[0].([]*resource.ResourceWithPipeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterDueResources indicates an expected call of FilterDueResources.
func (mr *ResourceRepositoryMockRecorder) FilterDueResources(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterDueResources", reflect.TypeOf((*ResourceRepository)(nil).FilterDueResources), ctx)
}

// FilterVersions mocks base method.
func (m *ResourceRepository) FilterVersions(ctx context.Context, tc, pn, rCan string) ([]*resource.Version, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterVersions", ctx, tc, pn, rCan)
	ret0, _ := ret[0].([]*resource.Version)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterVersions indicates an expected call of FilterVersions.
func (mr *ResourceRepositoryMockRecorder) FilterVersions(ctx, tc, pn, rCan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterVersions", reflect.TypeOf((*ResourceRepository)(nil).FilterVersions), ctx, tc, pn, rCan)
}

// Find mocks base method.
func (m *ResourceRepository) Find(ctx context.Context, tc, pn, rCan string) (*resource.Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, tc, pn, rCan)
	ret0, _ := ret[0].(*resource.Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *ResourceRepositoryMockRecorder) Find(ctx, tc, pn, rCan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*ResourceRepository)(nil).Find), ctx, tc, pn, rCan)
}

// FindByWebhookToken mocks base method.
func (m *ResourceRepository) FindByWebhookToken(ctx context.Context, token string) (*resource.Resource, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByWebhookToken", ctx, token)
	ret0, _ := ret[0].(*resource.Resource)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// FindByWebhookToken indicates an expected call of FindByWebhookToken.
func (mr *ResourceRepositoryMockRecorder) FindByWebhookToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByWebhookToken", reflect.TypeOf((*ResourceRepository)(nil).FindByWebhookToken), ctx, token)
}

// Update mocks base method.
func (m *ResourceRepository) Update(ctx context.Context, tc, pn, rCan string, r resource.Resource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tc, pn, rCan, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *ResourceRepositoryMockRecorder) Update(ctx, tc, pn, rCan, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*ResourceRepository)(nil).Update), ctx, tc, pn, rCan, r)
}
