// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xescugc/pikoci/pikoci/secret (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/secret_repository.go -mock_names=Repository=SecretRepository -package mock github.com/xescugc/pikoci/pikoci/secret Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	secret "github.com/xescugc/pikoci/pikoci/secret"
	gomock "go.uber.org/mock/gomock"
)

// SecretRepository is a mock of Repository interface.
type SecretRepository struct {
	ctrl     *gomock.Controller
	recorder *SecretRepositoryMockRecorder
	isgomock struct{}
}

// SecretRepositoryMockRecorder is the mock recorder for SecretRepository.
type SecretRepositoryMockRecorder struct {
	mock *SecretRepository
}

// NewSecretRepository creates a new mock instance.
func NewSecretRepository(ctrl *gomock.Controller) *SecretRepository {
	mock := &SecretRepository{ctrl: ctrl}
	mock.recorder = &SecretRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *SecretRepository) EXPECT() *SecretRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *SecretRepository) Create(ctx context.Context, tc, pn string, s secret.Secret) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tc, pn, s)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *SecretRepositoryMockRecorder) Create(ctx, tc, pn, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*SecretRepository)(nil).Create), ctx, tc, pn, s)
}

// Delete mocks base method.
func (m *SecretRepository) Delete(ctx context.Context, tc, pn, sCan string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tc, pn, sCan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *SecretRepositoryMockRecorder) Delete(ctx, tc, pn, sCan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*SecretRepository)(nil).Delete), ctx, tc, pn, sCan)
}

// Filter mocks base method.
func (m *SecretRepository) Filter(ctx context.Context, tc, pn string) ([]*secret.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, tc, pn)
	ret0, _ := ret[0].([]*secret.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *SecretRepositoryMockRecorder) Filter(ctx, tc, pn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*SecretRepository)(nil).Filter), ctx, tc, pn)
}

// Find mocks base method.
func (m *SecretRepository) Find(ctx context.Context, tc, pn, sCan string) (*secret.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, tc, pn, sCan)
	ret0, _ := ret[0].(*secret.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *SecretRepositoryMockRecorder) Find(ctx, tc, pn, sCan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*SecretRepository)(nil).Find), ctx, tc, pn, sCan)
}

// Update mocks base method.
func (m *SecretRepository) Update(ctx context.Context, tc, pn, sCan string, s secret.Secret) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tc, pn, sCan, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *SecretRepositoryMockRecorder) Update(ctx, tc, pn, sCan, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*SecretRepository)(nil).Update), ctx, tc, pn, sCan, s)
}
