// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xescugc/pikoci/pikoci/sectype (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/secret_type_repository.go -mock_names=Repository=SecretTypeRepository -package mock github.com/xescugc/pikoci/pikoci/sectype Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	sectype "github.com/xescugc/pikoci/pikoci/sectype"
	gomock "go.uber.org/mock/gomock"
)

// SecretTypeRepository is a mock of Repository interface.
type SecretTypeRepository struct {
	ctrl     *gomock.Controller
	recorder *SecretTypeRepositoryMockRecorder
	isgomock struct{}
}

// SecretTypeRepositoryMockRecorder is the mock recorder for SecretTypeRepository.
type SecretTypeRepositoryMockRecorder struct {
	mock *SecretTypeRepository
}

// NewSecretTypeRepository creates a new mock instance.
func NewSecretTypeRepository(ctrl *gomock.Controller) *SecretTypeRepository {
	mock := &SecretTypeRepository{ctrl: ctrl}
	mock.recorder = &SecretTypeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *SecretTypeRepository) EXPECT() *SecretTypeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *SecretTypeRepository) Create(ctx context.Context, tc, pn string, st sectype.SecretType) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tc, pn, st)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *SecretTypeRepositoryMockRecorder) Create(ctx, tc, pn, st any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*SecretTypeRepository)(nil).Create), ctx, tc, pn, st)
}

// Delete mocks base method.
func (m *SecretTypeRepository) Delete(ctx context.Context, tc, pn, stn string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tc, pn, stn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *SecretTypeRepositoryMockRecorder) Delete(ctx, tc, pn, stn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*SecretTypeRepository)(nil).Delete), ctx, tc, pn, stn)
}

// Filter mocks base method.
func (m *SecretTypeRepository) Filter(ctx context.Context, tc, pn string) ([]*sectype.SecretType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, tc, pn)
	ret0, _ := ret[0].([]*sectype.SecretType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *SecretTypeRepositoryMockRecorder) Filter(ctx, tc, pn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*SecretTypeRepository)(nil).Filter), ctx, tc, pn)
}

// Find mocks base method.
func (m *SecretTypeRepository) Find(ctx context.Context, tc, pn, stn string) (*sectype.SecretType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, tc, pn, stn)
	ret0, _ := ret[0].(*sectype.SecretType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *SecretTypeRepositoryMockRecorder) Find(ctx, tc, pn, stn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*SecretTypeRepository)(nil).Find), ctx, tc, pn, stn)
}

// Update mocks base method.
func (m *SecretTypeRepository) Update(ctx context.Context, tc, pn, stn string, st sectype.SecretType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tc, pn, stn, st)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *SecretTypeRepositoryMockRecorder) Update(ctx, tc, pn, stn, st any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*SecretTypeRepository)(nil).Update), ctx, tc, pn, stn, st)
}
