// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xescugc/qid/qid/runner (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/runner_repository.go -mock_names=Repository=RunnerRepository -package mock github.com/xescugc/qid/qid/runner Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	runner "github.com/xescugc/qid/qid/runner"
	gomock "go.uber.org/mock/gomock"
)

// RunnerRepository is a mock of Repository interface.
type RunnerRepository struct {
	ctrl     *gomock.Controller
	recorder *RunnerRepositoryMockRecorder
	isgomock struct{}
}

// RunnerRepositoryMockRecorder is the mock recorder for RunnerRepository.
type RunnerRepositoryMockRecorder struct {
	mock *RunnerRepository
}

// NewRunnerRepository creates a new mock instance.
func NewRunnerRepository(ctrl *gomock.Controller) *RunnerRepository {
	mock := &RunnerRepository{ctrl: ctrl}
	mock.recorder = &RunnerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *RunnerRepository) EXPECT() *RunnerRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *RunnerRepository) Create(ctx context.Context, pn string, ru runner.Runner) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pn, ru)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *RunnerRepositoryMockRecorder) Create(ctx, pn, ru any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*RunnerRepository)(nil).Create), ctx, pn, ru)
}

// Delete mocks base method.
func (m *RunnerRepository) Delete(ctx context.Context, pn, run string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, pn, run)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *RunnerRepositoryMockRecorder) Delete(ctx, pn, run any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*RunnerRepository)(nil).Delete), ctx, pn, run)
}

// Filter mocks base method.
func (m *RunnerRepository) Filter(ctx context.Context, pn string) ([]*runner.Runner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, pn)
	ret0, _ := ret[0].([]*runner.Runner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *RunnerRepositoryMockRecorder) Filter(ctx, pn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*RunnerRepository)(nil).Filter), ctx, pn)
}

// Find mocks base method.
func (m *RunnerRepository) Find(ctx context.Context, pn, run string) (*runner.Runner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, pn, run)
	ret0, _ := ret[0].(*runner.Runner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *RunnerRepositoryMockRecorder) Find(ctx, pn, run any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*RunnerRepository)(nil).Find), ctx, pn, run)
}

// Update mocks base method.
func (m *RunnerRepository) Update(ctx context.Context, pn, run string, ru runner.Runner) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, pn, run, ru)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *RunnerRepositoryMockRecorder) Update(ctx, pn, run, ru any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*RunnerRepository)(nil).Update), ctx, pn, run, ru)
}
