// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xescugc/qid/qid/queue (interfaces: Subscription)
//
// Generated by this command:
//
//	mockgen -destination=../mock/subscription.go -mock_names=Subscription=Subscription -package mock github.com/xescugc/qid/qid/queue Subscription
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	pubsub "gocloud.dev/pubsub"
)

// Subscription is a mock of Subscription interface.
type Subscription struct {
	ctrl     *gomock.Controller
	recorder *SubscriptionMockRecorder
	isgomock struct{}
}

// SubscriptionMockRecorder is the mock recorder for Subscription.
type SubscriptionMockRecorder struct {
	mock *Subscription
}

// NewSubscription creates a new mock instance.
func NewSubscription(ctrl *gomock.Controller) *Subscription {
	mock := &Subscription{ctrl: ctrl}
	mock.recorder = &SubscriptionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Subscription) EXPECT() *SubscriptionMockRecorder {
	return m.recorder
}

// As mocks base method.
func (m *Subscription) As(i any) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "As", i)
	ret0, _ := ret[0].(bool)
	return ret0
}

// As indicates an expected call of As.
func (mr *SubscriptionMockRecorder) As(i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "As", reflect.TypeOf((*Subscription)(nil).As), i)
}

// ErrorAs mocks base method.
func (m *Subscription) ErrorAs(err error, i any) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ErrorAs", err, i)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ErrorAs indicates an expected call of ErrorAs.
func (mr *SubscriptionMockRecorder) ErrorAs(err, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorAs", reflect.TypeOf((*Subscription)(nil).ErrorAs), err, i)
}

// Receive mocks base method.
func (m *Subscription) Receive(ctx context.Context) (*pubsub.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Receive", ctx)
	ret0, _ := ret[0].(*pubsub.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Receive indicates an expected call of Receive.
func (mr *SubscriptionMockRecorder) Receive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Receive", reflect.TypeOf((*Subscription)(nil).Receive), ctx)
}

// Shutdown mocks base method.
func (m *Subscription) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *SubscriptionMockRecorder) Shutdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*Subscription)(nil).Shutdown), ctx)
}
