// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xescugc/qid/qid/team (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/team_repository.go -mock_names=Repository=TeamRepository -package mock github.com/xescugc/qid/qid/team Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	team "github.com/xescugc/qid/qid/team"
	gomock "go.uber.org/mock/gomock"
)

// TeamRepository is a mock of Repository interface.
type TeamRepository struct {
	ctrl     *gomock.Controller
	recorder *TeamRepositoryMockRecorder
	isgomock struct{}
}

// TeamRepositoryMockRecorder is the mock recorder for TeamRepository.
type TeamRepositoryMockRecorder struct {
	mock *TeamRepository
}

// NewTeamRepository creates a new mock instance.
func NewTeamRepository(ctrl *gomock.Controller) *TeamRepository {
	mock := &TeamRepository{ctrl: ctrl}
	mock.recorder = &TeamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *TeamRepository) EXPECT() *TeamRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *TeamRepository) Create(ctx context.Context, t team.Team) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, t)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *TeamRepositoryMockRecorder) Create(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*TeamRepository)(nil).Create), ctx, t)
}

// CreateMember mocks base method.
func (m *TeamRepository) CreateMember(ctx context.Context, tc, mc string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMember", ctx, tc, mc)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMember indicates an expected call of CreateMember.
func (mr *TeamRepositoryMockRecorder) CreateMember(ctx, tc, mc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMember", reflect.TypeOf((*TeamRepository)(nil).CreateMember), ctx, tc, mc)
}

// Delete mocks base method.
func (m *TeamRepository) Delete(ctx context.Context, tc string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *TeamRepositoryMockRecorder) Delete(ctx, tc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*TeamRepository)(nil).Delete), ctx, tc)
}

// DeleteMember mocks base method.
func (m *TeamRepository) DeleteMember(ctx context.Context, tc, mc string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMember", ctx, tc, mc)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMember indicates an expected call of DeleteMember.
func (mr *TeamRepositoryMockRecorder) DeleteMember(ctx, tc, mc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMember", reflect.TypeOf((*TeamRepository)(nil).DeleteMember), ctx, tc, mc)
}

// Filter mocks base method.
func (m *TeamRepository) Filter(ctx context.Context, un string) ([]*team.WithMembers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx, un)
	ret0, _ := ret[0].([]*team.WithMembers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *TeamRepositoryMockRecorder) Filter(ctx, un any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*TeamRepository)(nil).Filter), ctx, un)
}

// Find mocks base method.
func (m *TeamRepository) Find(ctx context.Context, tc string) (*team.WithMembers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, tc)
	ret0, _ := ret[0].(*team.WithMembers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *TeamRepositoryMockRecorder) Find(ctx, tc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*TeamRepository)(nil).Find), ctx, tc)
}

// FindMember mocks base method.
func (m *TeamRepository) FindMember(ctx context.Context, tc, mc string) (*team.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMember", ctx, tc, mc)
	ret0, _ := ret[0].(*team.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMember indicates an expected call of FindMember.
func (mr *TeamRepositoryMockRecorder) FindMember(ctx, tc, mc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMember", reflect.TypeOf((*TeamRepository)(nil).FindMember), ctx, tc, mc)
}

// Update mocks base method.
func (m *TeamRepository) Update(ctx context.Context, tc string, t team.Team) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tc, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *TeamRepositoryMockRecorder) Update(ctx, tc, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*TeamRepository)(nil).Update), ctx, tc, t)
}
