// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xescugc/qid/qid/user (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/user_repository.go -mock_names=Repository=UserRepository -package mock github.com/xescugc/qid/qid/user Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	user "github.com/xescugc/qid/qid/user"
	gomock "go.uber.org/mock/gomock"
)

// UserRepository is a mock of Repository interface.
type UserRepository struct {
	ctrl     *gomock.Controller
	recorder *UserRepositoryMockRecorder
	isgomock struct{}
}

// UserRepositoryMockRecorder is the mock recorder for UserRepository.
type UserRepositoryMockRecorder struct {
	mock *UserRepository
}

// NewUserRepository creates a new mock instance.
func NewUserRepository(ctrl *gomock.Controller) *UserRepository {
	mock := &UserRepository{ctrl: ctrl}
	mock.recorder = &UserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *UserRepository) EXPECT() *UserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *UserRepository) Create(ctx context.Context, u user.User) (uint32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, u)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *UserRepositoryMockRecorder) Create(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*UserRepository)(nil).Create), ctx, u)
}

// Delete mocks base method.
func (m *UserRepository) Delete(ctx context.Context, un string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, un)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *UserRepositoryMockRecorder) Delete(ctx, un any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*UserRepository)(nil).Delete), ctx, un)
}

// Filter mocks base method.
func (m *UserRepository) Filter(ctx context.Context) ([]*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", ctx)
	ret0, _ := ret[0].([]*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter.
func (mr *UserRepositoryMockRecorder) Filter(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*UserRepository)(nil).Filter), ctx)
}

// Find mocks base method.
func (m *UserRepository) Find(ctx context.Context, un string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, un)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *UserRepositoryMockRecorder) Find(ctx, un any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*UserRepository)(nil).Find), ctx, un)
}

// FindWithMemberships mocks base method.
func (m *UserRepository) FindWithMemberships(ctx context.Context, un string) (*user.WithMemberships, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithMemberships", ctx, un)
	ret0, _ := ret[0].(*user.WithMemberships)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWithMemberships indicates an expected call of FindWithMemberships.
func (mr *UserRepositoryMockRecorder) FindWithMemberships(ctx, un any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithMemberships", reflect.TypeOf((*UserRepository)(nil).FindWithMemberships), ctx, un)
}

// Update mocks base method.
func (m *UserRepository) Update(ctx context.Context, un string, u user.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, un, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *UserRepositoryMockRecorder) Update(ctx, un, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*UserRepository)(nil).Update), ctx, un, u)
}
