services:
  qid:
    image: golang:1.25.1 
    ports:
      - '4000:4000'
    volumes:
      - ..:/go/src/qid
      - $GOPATH/pkg/mod:/go/pkg/mod
      - $GOCACHE:/root/.cache/go-build
    working_dir: /go/src/qid
    environment:
      - PORT=4000
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root123
      - DB_NAME=qid_develop
      - REDIS_ADDR=redis:6379
      - RUN_WORKER=true

  worker:
    image: golang:1.25.1 
    volumes:
      - ..:/go/src/qid
      - $GOPATH/pkg/mod:/go/pkg/mod
      - $GOCACHE:/root/.cache/go-build
    working_dir: /go/src/qid
    environment:
      - REDIS_ADDR=redis:6379
      - QID_URL=qid:4000
      - CONCURENCY=2

  asynqmon:
    image: hibiken/asynqmon:0.7.2
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - REDIS_ADDR=redis:6379

  mariadb:
    environment:
      - MYSQL_ROOT_PASSWORD=root123
    volumes:
      - ./data/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  redis:
    image: redis:8.2.1
    ports:
      - '6379:6379'

