services:
  qid:
    image: golang:1.25.1 
    ports:
      - '4000:4000'
    volumes:
      - ..:/go/src/qid
      - $GOPATH/pkg/mod:/go/pkg/mod
      - $GOCACHE:/root/.cache/go-build
    working_dir: /go/src/qid
    environment:
      - PORT=4000
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root123
      - DB_NAME=qid_develop
      - NATS_SERVER_URL=nats:4222
      - DB_MEM=true

  worker:
    image: golang:1.25.1 
    volumes:
      - ..:/go/src/qid
      - $GOPATH/pkg/mod:/go/pkg/mod
      - $GOCACHE:/root/.cache/go-build
    working_dir: /go/src/qid
    environment:
      - QID_URL=qid:4000
      - NATS_SERVER_URL=nats:4222


  nats:
    ports:
      # For clients
      - '4222:4222'
      # For HTTP management port for information reporting.
      - '8222:8222'

  mariadb:
    environment:
      - MYSQL_ROOT_PASSWORD=root123
    volumes:
      - ./data/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
