services:
  pikoci:
    #depends_on:
      #- mariadb
    networks:
      - pikoci
    volumes:
      - cache:/go

  worker:
    volumes:
      - cache:/go
    networks:
      - pikoci

  mariadb:
    image: mariadb:11.4.2
    networks:
      - pikoci

  nats:
    image: nats:2.12.0
    networks:
      - pikoci

  postgresql:
    image: postgres:17
    networks:
      - pikoci

  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - pikoci

  kafka:
    image: bitnami/kafka
    networks:
      - pikoci

  cockroachdb:
    image: cockroachdb/cockroach
    networks:
      - pikoci

  tidb:
    image: pingcap/tidb
    networks:
      - pikoci

volumes:
  cache:

networks:
  pikoci:
