// Code generated by "enumer -type=RouteName -transform=snake -output=route_names_string.go"; DO NOT EDIT.

package http

import (
	"fmt"
	"strings"
)

const _RouteNameName = "user_logincreate_userlist_userscreate_teamlist_teamsget_teamupdate_teamdelete_teamcreate_team_memberupdate_team_memberdelete_team_membercreate_pipelineupdate_pipelineget_pipelinedelete_pipelinelist_pipelinesget_pipeline_imagecreate_pipeline_imagetrigger_pipeline_jobget_pipeline_jobcreate_job_buildupdate_job_builddelete_job_buildlist_job_buildsget_pipeline_resourceupdate_pipeline_resourcetrigger_pipeline_resourcecreate_resource_versionlist_resource_versions"

var _RouteNameIndex = [...]uint16{0, 10, 21, 31, 42, 52, 60, 71, 82, 100, 118, 136, 151, 166, 178, 193, 207, 225, 246, 266, 282, 298, 314, 330, 345, 366, 390, 415, 438, 460}

const _RouteNameLowerName = "user_logincreate_userlist_userscreate_teamlist_teamsget_teamupdate_teamdelete_teamcreate_team_memberupdate_team_memberdelete_team_membercreate_pipelineupdate_pipelineget_pipelinedelete_pipelinelist_pipelinesget_pipeline_imagecreate_pipeline_imagetrigger_pipeline_jobget_pipeline_jobcreate_job_buildupdate_job_builddelete_job_buildlist_job_buildsget_pipeline_resourceupdate_pipeline_resourcetrigger_pipeline_resourcecreate_resource_versionlist_resource_versions"

func (i RouteName) String() string {
	if i < 0 || i >= RouteName(len(_RouteNameIndex)-1) {
		return fmt.Sprintf("RouteName(%d)", i)
	}
	return _RouteNameName[_RouteNameIndex[i]:_RouteNameIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _RouteNameNoOp() {
	var x [1]struct{}
	_ = x[UserLogin-(0)]
	_ = x[CreateUser-(1)]
	_ = x[ListUsers-(2)]
	_ = x[CreateTeam-(3)]
	_ = x[ListTeams-(4)]
	_ = x[GetTeam-(5)]
	_ = x[UpdateTeam-(6)]
	_ = x[DeleteTeam-(7)]
	_ = x[CreateTeamMember-(8)]
	_ = x[UpdateTeamMember-(9)]
	_ = x[DeleteTeamMember-(10)]
	_ = x[CreatePipeline-(11)]
	_ = x[UpdatePipeline-(12)]
	_ = x[GetPipeline-(13)]
	_ = x[DeletePipeline-(14)]
	_ = x[ListPipelines-(15)]
	_ = x[GetPipelineImage-(16)]
	_ = x[CreatePipelineImage-(17)]
	_ = x[TriggerPipelineJob-(18)]
	_ = x[GetPipelineJob-(19)]
	_ = x[CreateJobBuild-(20)]
	_ = x[UpdateJobBuild-(21)]
	_ = x[DeleteJobBuild-(22)]
	_ = x[ListJobBuilds-(23)]
	_ = x[GetPipelineResource-(24)]
	_ = x[UpdatePipelineResource-(25)]
	_ = x[TriggerPipelineResource-(26)]
	_ = x[CreateResourceVersion-(27)]
	_ = x[ListResourceVersions-(28)]
}

var _RouteNameValues = []RouteName{UserLogin, CreateUser, ListUsers, CreateTeam, ListTeams, GetTeam, UpdateTeam, DeleteTeam, CreateTeamMember, UpdateTeamMember, DeleteTeamMember, CreatePipeline, UpdatePipeline, GetPipeline, DeletePipeline, ListPipelines, GetPipelineImage, CreatePipelineImage, TriggerPipelineJob, GetPipelineJob, CreateJobBuild, UpdateJobBuild, DeleteJobBuild, ListJobBuilds, GetPipelineResource, UpdatePipelineResource, TriggerPipelineResource, CreateResourceVersion, ListResourceVersions}

var _RouteNameNameToValueMap = map[string]RouteName{
	_RouteNameName[0:10]:         UserLogin,
	_RouteNameLowerName[0:10]:    UserLogin,
	_RouteNameName[10:21]:        CreateUser,
	_RouteNameLowerName[10:21]:   CreateUser,
	_RouteNameName[21:31]:        ListUsers,
	_RouteNameLowerName[21:31]:   ListUsers,
	_RouteNameName[31:42]:        CreateTeam,
	_RouteNameLowerName[31:42]:   CreateTeam,
	_RouteNameName[42:52]:        ListTeams,
	_RouteNameLowerName[42:52]:   ListTeams,
	_RouteNameName[52:60]:        GetTeam,
	_RouteNameLowerName[52:60]:   GetTeam,
	_RouteNameName[60:71]:        UpdateTeam,
	_RouteNameLowerName[60:71]:   UpdateTeam,
	_RouteNameName[71:82]:        DeleteTeam,
	_RouteNameLowerName[71:82]:   DeleteTeam,
	_RouteNameName[82:100]:       CreateTeamMember,
	_RouteNameLowerName[82:100]:  CreateTeamMember,
	_RouteNameName[100:118]:      UpdateTeamMember,
	_RouteNameLowerName[100:118]: UpdateTeamMember,
	_RouteNameName[118:136]:      DeleteTeamMember,
	_RouteNameLowerName[118:136]: DeleteTeamMember,
	_RouteNameName[136:151]:      CreatePipeline,
	_RouteNameLowerName[136:151]: CreatePipeline,
	_RouteNameName[151:166]:      UpdatePipeline,
	_RouteNameLowerName[151:166]: UpdatePipeline,
	_RouteNameName[166:178]:      GetPipeline,
	_RouteNameLowerName[166:178]: GetPipeline,
	_RouteNameName[178:193]:      DeletePipeline,
	_RouteNameLowerName[178:193]: DeletePipeline,
	_RouteNameName[193:207]:      ListPipelines,
	_RouteNameLowerName[193:207]: ListPipelines,
	_RouteNameName[207:225]:      GetPipelineImage,
	_RouteNameLowerName[207:225]: GetPipelineImage,
	_RouteNameName[225:246]:      CreatePipelineImage,
	_RouteNameLowerName[225:246]: CreatePipelineImage,
	_RouteNameName[246:266]:      TriggerPipelineJob,
	_RouteNameLowerName[246:266]: TriggerPipelineJob,
	_RouteNameName[266:282]:      GetPipelineJob,
	_RouteNameLowerName[266:282]: GetPipelineJob,
	_RouteNameName[282:298]:      CreateJobBuild,
	_RouteNameLowerName[282:298]: CreateJobBuild,
	_RouteNameName[298:314]:      UpdateJobBuild,
	_RouteNameLowerName[298:314]: UpdateJobBuild,
	_RouteNameName[314:330]:      DeleteJobBuild,
	_RouteNameLowerName[314:330]: DeleteJobBuild,
	_RouteNameName[330:345]:      ListJobBuilds,
	_RouteNameLowerName[330:345]: ListJobBuilds,
	_RouteNameName[345:366]:      GetPipelineResource,
	_RouteNameLowerName[345:366]: GetPipelineResource,
	_RouteNameName[366:390]:      UpdatePipelineResource,
	_RouteNameLowerName[366:390]: UpdatePipelineResource,
	_RouteNameName[390:415]:      TriggerPipelineResource,
	_RouteNameLowerName[390:415]: TriggerPipelineResource,
	_RouteNameName[415:438]:      CreateResourceVersion,
	_RouteNameLowerName[415:438]: CreateResourceVersion,
	_RouteNameName[438:460]:      ListResourceVersions,
	_RouteNameLowerName[438:460]: ListResourceVersions,
}

var _RouteNameNames = []string{
	_RouteNameName[0:10],
	_RouteNameName[10:21],
	_RouteNameName[21:31],
	_RouteNameName[31:42],
	_RouteNameName[42:52],
	_RouteNameName[52:60],
	_RouteNameName[60:71],
	_RouteNameName[71:82],
	_RouteNameName[82:100],
	_RouteNameName[100:118],
	_RouteNameName[118:136],
	_RouteNameName[136:151],
	_RouteNameName[151:166],
	_RouteNameName[166:178],
	_RouteNameName[178:193],
	_RouteNameName[193:207],
	_RouteNameName[207:225],
	_RouteNameName[225:246],
	_RouteNameName[246:266],
	_RouteNameName[266:282],
	_RouteNameName[282:298],
	_RouteNameName[298:314],
	_RouteNameName[314:330],
	_RouteNameName[330:345],
	_RouteNameName[345:366],
	_RouteNameName[366:390],
	_RouteNameName[390:415],
	_RouteNameName[415:438],
	_RouteNameName[438:460],
}

// RouteNameString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func RouteNameString(s string) (RouteName, error) {
	if val, ok := _RouteNameNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _RouteNameNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to RouteName values", s)
}

// RouteNameValues returns all values of the enum
func RouteNameValues() []RouteName {
	return _RouteNameValues
}

// RouteNameStrings returns a slice of all String values of the enum
func RouteNameStrings() []string {
	strs := make([]string, len(_RouteNameNames))
	copy(strs, _RouteNameNames)
	return strs
}

// IsARouteName returns "true" if the value is listed in the enum definition. "false" otherwise
func (i RouteName) IsARouteName() bool {
	for _, v := range _RouteNameValues {
		if i == v {
			return true
		}
	}
	return false
}
