// Code generated by "enumer -type=RouteName -transform=snake -output=route_names_string.go"; DO NOT EDIT.

package http

import (
	"fmt"
	"strings"
)

const _RouteNameName = "user_loginrefresh_tokencreate_userlist_userscreate_teamlist_teamsget_teamupdate_teamdelete_teamcreate_team_memberupdate_team_memberdelete_team_membercreate_pipelineupdate_pipelineget_pipelinedelete_pipelinelist_pipelinesget_pipeline_imagecreate_pipeline_imagetrigger_pipeline_jobget_pipeline_jobcreate_job_buildupdate_job_builddelete_job_buildlist_job_buildsget_pipeline_resourceupdate_pipeline_resourcetrigger_pipeline_resourcecreate_resource_versionlist_resource_versionswebhook_triggerregenerate_webhook_token"

var _RouteNameIndex = [...]uint16{0, 10, 23, 34, 44, 55, 65, 73, 84, 95, 113, 131, 149, 164, 179, 191, 206, 220, 238, 259, 279, 295, 311, 327, 343, 358, 379, 403, 428, 451, 473, 488, 512}

const _RouteNameLowerName = "user_loginrefresh_tokencreate_userlist_userscreate_teamlist_teamsget_teamupdate_teamdelete_teamcreate_team_memberupdate_team_memberdelete_team_membercreate_pipelineupdate_pipelineget_pipelinedelete_pipelinelist_pipelinesget_pipeline_imagecreate_pipeline_imagetrigger_pipeline_jobget_pipeline_jobcreate_job_buildupdate_job_builddelete_job_buildlist_job_buildsget_pipeline_resourceupdate_pipeline_resourcetrigger_pipeline_resourcecreate_resource_versionlist_resource_versionswebhook_triggerregenerate_webhook_token"

func (i RouteName) String() string {
	if i < 0 || i >= RouteName(len(_RouteNameIndex)-1) {
		return fmt.Sprintf("RouteName(%d)", i)
	}
	return _RouteNameName[_RouteNameIndex[i]:_RouteNameIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _RouteNameNoOp() {
	var x [1]struct{}
	_ = x[UserLogin-(0)]
	_ = x[RefreshToken-(1)]
	_ = x[CreateUser-(2)]
	_ = x[ListUsers-(3)]
	_ = x[CreateTeam-(4)]
	_ = x[ListTeams-(5)]
	_ = x[GetTeam-(6)]
	_ = x[UpdateTeam-(7)]
	_ = x[DeleteTeam-(8)]
	_ = x[CreateTeamMember-(9)]
	_ = x[UpdateTeamMember-(10)]
	_ = x[DeleteTeamMember-(11)]
	_ = x[CreatePipeline-(12)]
	_ = x[UpdatePipeline-(13)]
	_ = x[GetPipeline-(14)]
	_ = x[DeletePipeline-(15)]
	_ = x[ListPipelines-(16)]
	_ = x[GetPipelineImage-(17)]
	_ = x[CreatePipelineImage-(18)]
	_ = x[TriggerPipelineJob-(19)]
	_ = x[GetPipelineJob-(20)]
	_ = x[CreateJobBuild-(21)]
	_ = x[UpdateJobBuild-(22)]
	_ = x[DeleteJobBuild-(23)]
	_ = x[ListJobBuilds-(24)]
	_ = x[GetPipelineResource-(25)]
	_ = x[UpdatePipelineResource-(26)]
	_ = x[TriggerPipelineResource-(27)]
	_ = x[CreateResourceVersion-(28)]
	_ = x[ListResourceVersions-(29)]
	_ = x[WebhookTrigger-(30)]
	_ = x[RegenerateWebhookToken-(31)]
}

var _RouteNameValues = []RouteName{UserLogin, RefreshToken, CreateUser, ListUsers, CreateTeam, ListTeams, GetTeam, UpdateTeam, DeleteTeam, CreateTeamMember, UpdateTeamMember, DeleteTeamMember, CreatePipeline, UpdatePipeline, GetPipeline, DeletePipeline, ListPipelines, GetPipelineImage, CreatePipelineImage, TriggerPipelineJob, GetPipelineJob, CreateJobBuild, UpdateJobBuild, DeleteJobBuild, ListJobBuilds, GetPipelineResource, UpdatePipelineResource, TriggerPipelineResource, CreateResourceVersion, ListResourceVersions, WebhookTrigger, RegenerateWebhookToken}

var _RouteNameNameToValueMap = map[string]RouteName{
	_RouteNameName[0:10]:         UserLogin,
	_RouteNameLowerName[0:10]:    UserLogin,
	_RouteNameName[10:23]:        RefreshToken,
	_RouteNameLowerName[10:23]:   RefreshToken,
	_RouteNameName[23:34]:        CreateUser,
	_RouteNameLowerName[23:34]:   CreateUser,
	_RouteNameName[34:44]:        ListUsers,
	_RouteNameLowerName[34:44]:   ListUsers,
	_RouteNameName[44:55]:        CreateTeam,
	_RouteNameLowerName[44:55]:   CreateTeam,
	_RouteNameName[55:65]:        ListTeams,
	_RouteNameLowerName[55:65]:   ListTeams,
	_RouteNameName[65:73]:        GetTeam,
	_RouteNameLowerName[65:73]:   GetTeam,
	_RouteNameName[73:84]:        UpdateTeam,
	_RouteNameLowerName[73:84]:   UpdateTeam,
	_RouteNameName[84:95]:        DeleteTeam,
	_RouteNameLowerName[84:95]:   DeleteTeam,
	_RouteNameName[95:113]:       CreateTeamMember,
	_RouteNameLowerName[95:113]:  CreateTeamMember,
	_RouteNameName[113:131]:      UpdateTeamMember,
	_RouteNameLowerName[113:131]: UpdateTeamMember,
	_RouteNameName[131:149]:      DeleteTeamMember,
	_RouteNameLowerName[131:149]: DeleteTeamMember,
	_RouteNameName[149:164]:      CreatePipeline,
	_RouteNameLowerName[149:164]: CreatePipeline,
	_RouteNameName[164:179]:      UpdatePipeline,
	_RouteNameLowerName[164:179]: UpdatePipeline,
	_RouteNameName[179:191]:      GetPipeline,
	_RouteNameLowerName[179:191]: GetPipeline,
	_RouteNameName[191:206]:      DeletePipeline,
	_RouteNameLowerName[191:206]: DeletePipeline,
	_RouteNameName[206:220]:      ListPipelines,
	_RouteNameLowerName[206:220]: ListPipelines,
	_RouteNameName[220:238]:      GetPipelineImage,
	_RouteNameLowerName[220:238]: GetPipelineImage,
	_RouteNameName[238:259]:      CreatePipelineImage,
	_RouteNameLowerName[238:259]: CreatePipelineImage,
	_RouteNameName[259:279]:      TriggerPipelineJob,
	_RouteNameLowerName[259:279]: TriggerPipelineJob,
	_RouteNameName[279:295]:      GetPipelineJob,
	_RouteNameLowerName[279:295]: GetPipelineJob,
	_RouteNameName[295:311]:      CreateJobBuild,
	_RouteNameLowerName[295:311]: CreateJobBuild,
	_RouteNameName[311:327]:      UpdateJobBuild,
	_RouteNameLowerName[311:327]: UpdateJobBuild,
	_RouteNameName[327:343]:      DeleteJobBuild,
	_RouteNameLowerName[327:343]: DeleteJobBuild,
	_RouteNameName[343:358]:      ListJobBuilds,
	_RouteNameLowerName[343:358]: ListJobBuilds,
	_RouteNameName[358:379]:      GetPipelineResource,
	_RouteNameLowerName[358:379]: GetPipelineResource,
	_RouteNameName[379:403]:      UpdatePipelineResource,
	_RouteNameLowerName[379:403]: UpdatePipelineResource,
	_RouteNameName[403:428]:      TriggerPipelineResource,
	_RouteNameLowerName[403:428]: TriggerPipelineResource,
	_RouteNameName[428:451]:      CreateResourceVersion,
	_RouteNameLowerName[428:451]: CreateResourceVersion,
	_RouteNameName[451:473]:      ListResourceVersions,
	_RouteNameLowerName[451:473]: ListResourceVersions,
	_RouteNameName[473:488]:      WebhookTrigger,
	_RouteNameLowerName[473:488]: WebhookTrigger,
	_RouteNameName[488:512]:      RegenerateWebhookToken,
	_RouteNameLowerName[488:512]: RegenerateWebhookToken,
}

var _RouteNameNames = []string{
	_RouteNameName[0:10],
	_RouteNameName[10:23],
	_RouteNameName[23:34],
	_RouteNameName[34:44],
	_RouteNameName[44:55],
	_RouteNameName[55:65],
	_RouteNameName[65:73],
	_RouteNameName[73:84],
	_RouteNameName[84:95],
	_RouteNameName[95:113],
	_RouteNameName[113:131],
	_RouteNameName[131:149],
	_RouteNameName[149:164],
	_RouteNameName[164:179],
	_RouteNameName[179:191],
	_RouteNameName[191:206],
	_RouteNameName[206:220],
	_RouteNameName[220:238],
	_RouteNameName[238:259],
	_RouteNameName[259:279],
	_RouteNameName[279:295],
	_RouteNameName[295:311],
	_RouteNameName[311:327],
	_RouteNameName[327:343],
	_RouteNameName[343:358],
	_RouteNameName[358:379],
	_RouteNameName[379:403],
	_RouteNameName[403:428],
	_RouteNameName[428:451],
	_RouteNameName[451:473],
	_RouteNameName[473:488],
	_RouteNameName[488:512],
}

// RouteNameString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func RouteNameString(s string) (RouteName, error) {
	if val, ok := _RouteNameNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _RouteNameNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to RouteName values", s)
}

// RouteNameValues returns all values of the enum
func RouteNameValues() []RouteName {
	return _RouteNameValues
}

// RouteNameStrings returns a slice of all String values of the enum
func RouteNameStrings() []string {
	strs := make([]string, len(_RouteNameNames))
	copy(strs, _RouteNameNames)
	return strs
}

// IsARouteName returns "true" if the value is listed in the enum definition. "false" otherwise
func (i RouteName) IsARouteName() bool {
	for _, v := range _RouteNameValues {
		if i == v {
			return true
		}
	}
	return false
}
