// Code generated by "enumer -type=RouteName -transform=snake -output=route_names_string.go"; DO NOT EDIT.

package http

import (
	"fmt"
	"strings"
)

const _RouteNameName = "user_loginrefresh_tokencreate_userlist_userscreate_teamlist_teamsget_teamupdate_teamdelete_teamcreate_team_memberupdate_team_memberdelete_team_membercreate_pipelineupdate_pipelineget_pipelinedelete_pipelinelist_pipelinesget_pipeline_imagecreate_pipeline_imagetrigger_pipeline_jobget_pipeline_jobcreate_job_buildcreate_retry_job_buildupdate_job_builddelete_job_buildlist_job_buildsinsert_build_get_versionfind_build_get_versionsget_job_buildcancel_job_buildretry_job_buildget_pipeline_resourceupdate_pipeline_resourcetrigger_pipeline_resourcecreate_resource_versionlist_resource_versionswebhook_triggerregenerate_webhook_token"

var _RouteNameIndex = [...]uint16{0, 10, 23, 34, 44, 55, 65, 73, 84, 95, 113, 131, 149, 164, 179, 191, 206, 220, 238, 259, 279, 295, 311, 333, 349, 365, 380, 404, 427, 440, 456, 471, 492, 516, 541, 564, 586, 601, 625}

const _RouteNameLowerName = "user_loginrefresh_tokencreate_userlist_userscreate_teamlist_teamsget_teamupdate_teamdelete_teamcreate_team_memberupdate_team_memberdelete_team_membercreate_pipelineupdate_pipelineget_pipelinedelete_pipelinelist_pipelinesget_pipeline_imagecreate_pipeline_imagetrigger_pipeline_jobget_pipeline_jobcreate_job_buildcreate_retry_job_buildupdate_job_builddelete_job_buildlist_job_buildsinsert_build_get_versionfind_build_get_versionsget_job_buildcancel_job_buildretry_job_buildget_pipeline_resourceupdate_pipeline_resourcetrigger_pipeline_resourcecreate_resource_versionlist_resource_versionswebhook_triggerregenerate_webhook_token"

func (i RouteName) String() string {
	if i < 0 || i >= RouteName(len(_RouteNameIndex)-1) {
		return fmt.Sprintf("RouteName(%d)", i)
	}
	return _RouteNameName[_RouteNameIndex[i]:_RouteNameIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _RouteNameNoOp() {
	var x [1]struct{}
	_ = x[UserLogin-(0)]
	_ = x[RefreshToken-(1)]
	_ = x[CreateUser-(2)]
	_ = x[ListUsers-(3)]
	_ = x[CreateTeam-(4)]
	_ = x[ListTeams-(5)]
	_ = x[GetTeam-(6)]
	_ = x[UpdateTeam-(7)]
	_ = x[DeleteTeam-(8)]
	_ = x[CreateTeamMember-(9)]
	_ = x[UpdateTeamMember-(10)]
	_ = x[DeleteTeamMember-(11)]
	_ = x[CreatePipeline-(12)]
	_ = x[UpdatePipeline-(13)]
	_ = x[GetPipeline-(14)]
	_ = x[DeletePipeline-(15)]
	_ = x[ListPipelines-(16)]
	_ = x[GetPipelineImage-(17)]
	_ = x[CreatePipelineImage-(18)]
	_ = x[TriggerPipelineJob-(19)]
	_ = x[GetPipelineJob-(20)]
	_ = x[CreateJobBuild-(21)]
	_ = x[CreateRetryJobBuild-(22)]
	_ = x[UpdateJobBuild-(23)]
	_ = x[DeleteJobBuild-(24)]
	_ = x[ListJobBuilds-(25)]
	_ = x[InsertBuildGetVersion-(26)]
	_ = x[FindBuildGetVersions-(27)]
	_ = x[GetJobBuild-(28)]
	_ = x[CancelJobBuild-(29)]
	_ = x[RetryJobBuild-(30)]
	_ = x[GetPipelineResource-(31)]
	_ = x[UpdatePipelineResource-(32)]
	_ = x[TriggerPipelineResource-(33)]
	_ = x[CreateResourceVersion-(34)]
	_ = x[ListResourceVersions-(35)]
	_ = x[WebhookTrigger-(36)]
	_ = x[RegenerateWebhookToken-(37)]
}

var _RouteNameValues = []RouteName{UserLogin, RefreshToken, CreateUser, ListUsers, CreateTeam, ListTeams, GetTeam, UpdateTeam, DeleteTeam, CreateTeamMember, UpdateTeamMember, DeleteTeamMember, CreatePipeline, UpdatePipeline, GetPipeline, DeletePipeline, ListPipelines, GetPipelineImage, CreatePipelineImage, TriggerPipelineJob, GetPipelineJob, CreateJobBuild, CreateRetryJobBuild, UpdateJobBuild, DeleteJobBuild, ListJobBuilds, InsertBuildGetVersion, FindBuildGetVersions, GetJobBuild, CancelJobBuild, RetryJobBuild, GetPipelineResource, UpdatePipelineResource, TriggerPipelineResource, CreateResourceVersion, ListResourceVersions, WebhookTrigger, RegenerateWebhookToken}

var _RouteNameNameToValueMap = map[string]RouteName{
	_RouteNameName[0:10]:         UserLogin,
	_RouteNameLowerName[0:10]:    UserLogin,
	_RouteNameName[10:23]:        RefreshToken,
	_RouteNameLowerName[10:23]:   RefreshToken,
	_RouteNameName[23:34]:        CreateUser,
	_RouteNameLowerName[23:34]:   CreateUser,
	_RouteNameName[34:44]:        ListUsers,
	_RouteNameLowerName[34:44]:   ListUsers,
	_RouteNameName[44:55]:        CreateTeam,
	_RouteNameLowerName[44:55]:   CreateTeam,
	_RouteNameName[55:65]:        ListTeams,
	_RouteNameLowerName[55:65]:   ListTeams,
	_RouteNameName[65:73]:        GetTeam,
	_RouteNameLowerName[65:73]:   GetTeam,
	_RouteNameName[73:84]:        UpdateTeam,
	_RouteNameLowerName[73:84]:   UpdateTeam,
	_RouteNameName[84:95]:        DeleteTeam,
	_RouteNameLowerName[84:95]:   DeleteTeam,
	_RouteNameName[95:113]:       CreateTeamMember,
	_RouteNameLowerName[95:113]:  CreateTeamMember,
	_RouteNameName[113:131]:      UpdateTeamMember,
	_RouteNameLowerName[113:131]: UpdateTeamMember,
	_RouteNameName[131:149]:      DeleteTeamMember,
	_RouteNameLowerName[131:149]: DeleteTeamMember,
	_RouteNameName[149:164]:      CreatePipeline,
	_RouteNameLowerName[149:164]: CreatePipeline,
	_RouteNameName[164:179]:      UpdatePipeline,
	_RouteNameLowerName[164:179]: UpdatePipeline,
	_RouteNameName[179:191]:      GetPipeline,
	_RouteNameLowerName[179:191]: GetPipeline,
	_RouteNameName[191:206]:      DeletePipeline,
	_RouteNameLowerName[191:206]: DeletePipeline,
	_RouteNameName[206:220]:      ListPipelines,
	_RouteNameLowerName[206:220]: ListPipelines,
	_RouteNameName[220:238]:      GetPipelineImage,
	_RouteNameLowerName[220:238]: GetPipelineImage,
	_RouteNameName[238:259]:      CreatePipelineImage,
	_RouteNameLowerName[238:259]: CreatePipelineImage,
	_RouteNameName[259:279]:      TriggerPipelineJob,
	_RouteNameLowerName[259:279]: TriggerPipelineJob,
	_RouteNameName[279:295]:      GetPipelineJob,
	_RouteNameLowerName[279:295]: GetPipelineJob,
	_RouteNameName[295:311]:      CreateJobBuild,
	_RouteNameLowerName[295:311]: CreateJobBuild,
	_RouteNameName[311:333]:      CreateRetryJobBuild,
	_RouteNameLowerName[311:333]: CreateRetryJobBuild,
	_RouteNameName[333:349]:      UpdateJobBuild,
	_RouteNameLowerName[333:349]: UpdateJobBuild,
	_RouteNameName[349:365]:      DeleteJobBuild,
	_RouteNameLowerName[349:365]: DeleteJobBuild,
	_RouteNameName[365:380]:      ListJobBuilds,
	_RouteNameLowerName[365:380]: ListJobBuilds,
	_RouteNameName[380:404]:      InsertBuildGetVersion,
	_RouteNameLowerName[380:404]: InsertBuildGetVersion,
	_RouteNameName[404:427]:      FindBuildGetVersions,
	_RouteNameLowerName[404:427]: FindBuildGetVersions,
	_RouteNameName[427:440]:      GetJobBuild,
	_RouteNameLowerName[427:440]: GetJobBuild,
	_RouteNameName[440:456]:      CancelJobBuild,
	_RouteNameLowerName[440:456]: CancelJobBuild,
	_RouteNameName[456:471]:      RetryJobBuild,
	_RouteNameLowerName[456:471]: RetryJobBuild,
	_RouteNameName[471:492]:      GetPipelineResource,
	_RouteNameLowerName[471:492]: GetPipelineResource,
	_RouteNameName[492:516]:      UpdatePipelineResource,
	_RouteNameLowerName[492:516]: UpdatePipelineResource,
	_RouteNameName[516:541]:      TriggerPipelineResource,
	_RouteNameLowerName[516:541]: TriggerPipelineResource,
	_RouteNameName[541:564]:      CreateResourceVersion,
	_RouteNameLowerName[541:564]: CreateResourceVersion,
	_RouteNameName[564:586]:      ListResourceVersions,
	_RouteNameLowerName[564:586]: ListResourceVersions,
	_RouteNameName[586:601]:      WebhookTrigger,
	_RouteNameLowerName[586:601]: WebhookTrigger,
	_RouteNameName[601:625]:      RegenerateWebhookToken,
	_RouteNameLowerName[601:625]: RegenerateWebhookToken,
}

var _RouteNameNames = []string{
	_RouteNameName[0:10],
	_RouteNameName[10:23],
	_RouteNameName[23:34],
	_RouteNameName[34:44],
	_RouteNameName[44:55],
	_RouteNameName[55:65],
	_RouteNameName[65:73],
	_RouteNameName[73:84],
	_RouteNameName[84:95],
	_RouteNameName[95:113],
	_RouteNameName[113:131],
	_RouteNameName[131:149],
	_RouteNameName[149:164],
	_RouteNameName[164:179],
	_RouteNameName[179:191],
	_RouteNameName[191:206],
	_RouteNameName[206:220],
	_RouteNameName[220:238],
	_RouteNameName[238:259],
	_RouteNameName[259:279],
	_RouteNameName[279:295],
	_RouteNameName[295:311],
	_RouteNameName[311:333],
	_RouteNameName[333:349],
	_RouteNameName[349:365],
	_RouteNameName[365:380],
	_RouteNameName[380:404],
	_RouteNameName[404:427],
	_RouteNameName[427:440],
	_RouteNameName[440:456],
	_RouteNameName[456:471],
	_RouteNameName[471:492],
	_RouteNameName[492:516],
	_RouteNameName[516:541],
	_RouteNameName[541:564],
	_RouteNameName[564:586],
	_RouteNameName[586:601],
	_RouteNameName[601:625],
}

// RouteNameString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func RouteNameString(s string) (RouteName, error) {
	if val, ok := _RouteNameNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _RouteNameNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to RouteName values", s)
}

// RouteNameValues returns all values of the enum
func RouteNameValues() []RouteName {
	return _RouteNameValues
}

// RouteNameStrings returns a slice of all String values of the enum
func RouteNameStrings() []string {
	strs := make([]string, len(_RouteNameNames))
	copy(strs, _RouteNameNames)
	return strs
}

// IsARouteName returns "true" if the value is listed in the enum definition. "false" otherwise
func (i RouteName) IsARouteName() bool {
	for _, v := range _RouteNameValues {
		if i == v {
			return true
		}
	}
	return false
}
